export const GET_MAKES = 'GET_MAKES';
export const GET_MODELS = 'GET_MODELS';
export const IS_HAVE_CAR = 'IS_HAVE_CAR';
export const IS_SELECTED_MAKE_NAME = 'IS_SELECTED_MAKE_NAME';
export const IS_SELECTED_MODEL = 'IS_SELECTED_MODEL';
export const VALID_INPUT_PASSPORT = 'VALID_INPUT_PASSPORT';
export const VALID_INPUT_NAME = 'VALID_INPUT_NAME';
export const VALID_INPUT_SURNAME = 'VALID_INPUT_SURNAME';
export const VALID_INPUT_PATRONYMIC = 'VALID_INPUT_PATRONYMIC';
export const VALID_INPUT_EMAIL = 'VALID_INPUT_EMAIL';
export const IS_FETCHING = 'IS_FETCHING';
export const IS_SENDING = 'IS_SENDING';
export const IS_SENDING_DONE = 'IS_SENDING_DONE';
export const SET_GENDER = 'SET_GENDER';
export const SET_BIRTH_DATE = 'SET_BIRTH_DATE';
export const FORM_RESTORE_DEFAULT = 'FORM_RESTORE_DEFAULT';

